logging:
  level:
    com:
      paladin:
        vod:
          mapper: DEBUG

server:
  port: 9010

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    name: vod
    url: jdbc:mysql://172.16.16.120:3306/vod?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15
  thymeleaf:
    cache: false

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000


vod:
  # nginx访问视频地址
  rtmp-server-url: http://172.16.16.120:9999
  # ffmpeg工具地址（windows下好像无法通过配置的环境变量运行，需要完整目录，centos下可以直接ffmpeg）
  ffmpeg: E:/ffmpeg/bin/ffmpeg.exe
  # 视频上传存放目录
  upload:
    folder: E:/upload/
  # 视频转码后存放目录，该目录应该与nginx配置的视频目录一致，从而转码成功后即可通过nginx点播视频
  transcode:
    folder: E:/transcode/